"""`agent-settings <catalog.json> sync | select <launcher> [args] | launch [args]`."""

import json
import sys
from pathlib import Path
from typing import cast

from agent_settings.agents import create_agent
from agent_settings.catalog import Manifest
from agent_settings.errors import SettingsError


def run(argv: list[str]) -> None:
    catalog_path, command, *args = argv
    # The catalog is generated by withModelPicker.nix.
    agent = create_agent(cast(Manifest, json.loads(Path(catalog_path).read_text())))
    match command:
        case "sync":
            agent.sync()
        case "select":
            agent.select(args[0], args[1:])
        case "launch":
            agent.launch(args)
        case _:
            raise SettingsError(f"unknown action: {command}")


def main() -> None:
    try:
        run(sys.argv[1:])
    except KeyboardInterrupt:
        sys.exit(0)
    except (SettingsError, OSError, ValueError, KeyError, TypeError) as error:
        print(f"agent-settings: {error}", file=sys.stderr)
        sys.exit(1)
