// OpenCode 2 plugin: enforce per-provider model allow-lists and discover the
// tailnet AI proxy catalog.
//
// V2 dropped provider whitelist/blacklist, and config overrides cannot cover
// mode-expanded catalog entries ("gpt-5.6-fast"), so enforcement runs here on
// the assembled catalog. The proxy filters its own /models output
// server-side; this plugin imports that list and enriches it with models.dev
// metadata. Data lives in ../agent-models.json, generated by Home Manager.

import { readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join } from "node:path";

const configDir = join(
  process.env.XDG_CONFIG_HOME || join(homedir(), ".config"),
  "opencode",
);
const { allow = {}, proxy = null } = JSON.parse(
  await readFile(join(configDir, "agent-models.json"), "utf8"),
);

// Keep mode-expanded entries ("gpt-5.6-sol-fast") of allow-listed models.
function isAllowed(providerID, modelID) {
  const list = allow[providerID];
  if (!list) return true;
  return (
    list.includes(modelID) || list.some((id) => modelID.startsWith(id + "-"))
  );
}

async function discoverProxyModels() {
  if (!proxy) return [];
  const key = (await readFile(proxy.keyFile, "utf8")).trim();
  const res = await fetch(proxy.baseURL.replace(/\/+$/, "") + "/models", {
    headers: { authorization: "Bearer " + key },
    signal: AbortSignal.timeout(10000),
  });
  if (!res.ok) throw new Error("proxy /models returned " + res.status);
  const body = await res.json();
  return (body.data || []).map((m) => m.id);
}

// Metadata index over models.dev, keyed by bare model id.
async function fetchModelsDev() {
  const res = await fetch("https://models.dev/api.json", {
    signal: AbortSignal.timeout(10000),
  });
  if (!res.ok) throw new Error("models.dev returned " + res.status);
  const catalog = await res.json();
  const index = {};
  for (const provider of Object.values(catalog)) {
    for (const [id, model] of Object.entries(provider.models || {})) {
      index[id.split("/").pop()] = model;
    }
  }
  return index;
}

export default {
  id: "dotfiles.models",
  async setup(ctx) {
    const [proxyModels, modelsDev] = await Promise.all([
      discoverProxyModels().catch(() => []),
      fetchModelsDev().catch(() => ({})),
    ]);

    await ctx.catalog.transform((catalog) => {
      // The draft catalog only contains models.dev providers; the
      // config-defined proxy provider is created implicitly by updating its
      // models.
      if (proxy) {
        for (const id of proxyModels) {
          catalog.model.update(proxy.id, id, (model) => {
            const meta = modelsDev[id];
            if (!meta) return;
            if (meta.name) model.name = meta.name;
            if (meta.limit && meta.limit.context && meta.limit.output)
              model.limit = {
                context: meta.limit.context,
                output: meta.limit.output,
              };
            model.capabilities = model.capabilities || {};
            model.capabilities.tools = meta.tool_call !== false;
            if (meta.modalities) {
              model.capabilities.input = meta.modalities.input || ["text"];
              model.capabilities.output = meta.modalities.output || ["text"];
            }
          });
        }
      }
      for (const record of catalog.provider.list()) {
        const providerID = record.provider.id;
        for (const modelID of record.models.keys()) {
          if (!isAllowed(providerID, modelID))
            catalog.model.remove(providerID, modelID);
        }
      }
    });
  },
};
