# Shared hardware config for nixos-anywhere targets
#
# Each target gets its own {hostname}-generated.nix in this directory,
# auto-generated by nixos-anywhere via --generate-hardware-config.
#
# Usage:
#   1. Add a new host to flake.nix with hardware = "anywhere"
#   2. Create a placeholder: just add-anywhere <hostname>
#   3. Deploy: just deploy-anywhere <hostname> <ip>
#   4. git add hardware/<hostname>-generated.nix
{
  inputs,
  hostname,
  modulesPath,
  ...
}:

{
  imports = [
    inputs.disko.nixosModules.disko
    ./disko-config.nix
    (modulesPath + "/installer/scan/not-detected.nix")
    (modulesPath + "/profiles/qemu-guest.nix")
    # Per-host generated hardware config (created by nixos-anywhere)
    (./. + "/${hostname}-generated.nix")
  ];

  system.stateVersion = "25.11";

  # Bootloader - GRUB with EFI (compatible with disko)
  # devices is not needed; disko will add devices with EF02 partitions automatically
  boot.loader.grub = {
    devices = [ "nodev" ];
    efiSupport = true;
    efiInstallAsRemovable = true;
  };

  # SSH access (required for remote management after install)
  services.openssh.enable = true;
}
