apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - tailscale-ingress.yaml
images:
  - name: ghcr.io/whexy/<name>
    newTag: <version>
