apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <name>-tailscale
  namespace: <name>
  annotations:
    tailscale.com/proxy-group: ingress-proxies
spec:
  ingressClassName: tailscale
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <name>
                port:
                  number: <port>
  tls:
    - hosts:
        - <name>
