{ pkgs }:
let
  policies = pkgs.writeText "chromium-policies.json" (
    builtins.toJSON (import ../../modules/home/browser/chromium/shared.nix)
  );
  installer = pkgs.writeText "Install-ChromiumPolicy.ps1" ''
    # Generated by Nix. Run from WSL with: powershell.exe -ExecutionPolicy Bypass -File ...
    $ErrorActionPreference = "Stop"
    $root = "HKCU:\Software\Policies\Google\Chrome"
    New-Item -Path $root -Force | Out-Null
    $policies = Get-Content -Raw -LiteralPath (Join-Path $PSScriptRoot "chromium-policies.json") | ConvertFrom-Json
    foreach ($property in $policies.PSObject.Properties) {
      New-ItemProperty -Path $root -Name $property.Name -Value $property.Value -PropertyType String -Force | Out-Null
    }
    Write-Host "Chromium policies installed for the current Windows user. Restart Chrome to apply them."
  '';
in
pkgs.runCommand "chromium-windows-policy" { } ''
    mkdir -p $out
    cp ${policies} $out/chromium-policies.json
    cp ${installer} $out/Install-ChromiumPolicy.ps1
    cat > $out/README.md <<'EOF'
  Run `Install-ChromiumPolicy.ps1` from PowerShell. From WSL:

      powershell.exe -ExecutionPolicy Bypass -File ./Install-ChromiumPolicy.ps1

  The installer writes per-user Google Chrome policies under HKCU. Re-run it
  after changing the Nix source; Chrome must be restarted to reload policies.
  EOF
''
